### ISSUE TITLE
BUG: java.net.UnknownHostException: <domain>

### ISSUE THREAD

**Issue by ikoutone** [Scrin/RuuviCollector#51] opened 2020-07-25 12:44 UTC
**Describe the bug**
Jul 25, 2020 12:38:49 AM org.influxdb.impl.BatchProcessor write
SEVERE: Batch could not be sent. Data will be lost
org.influxdb.InfluxDBIOException: java.net.UnknownHostException: darkball.net
        at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:800)
        at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:455)
        at org.influxdb.impl.OneShotBatchWriter.write(OneShotBatchWriter.java:22)
        at org.influxdb.impl.BatchProcessor.write(BatchProcessor.java:321)
        at org.influxdb.impl.BatchProcessor$1.run(BatchProcessor.java:269)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: darkball.net
        at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
        at java.net.InetAddress.getAllByName(InetAddress.java:1193)
        at java.net.InetAddress.getAllByName(InetAddress.java:1127)
        at okhttp3.Dns$1.lookup(Dns.java:40)
        at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
        at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
        at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at org.influxdb.impl.BasicAuthInterceptor.intercept(BasicAuthInterceptor.java:22)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at org.influxdb.impl.GzipRequestInterceptor.intercept(GzipRequestInterceptor.java:53)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:144)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
        at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:788)
        ... 11 more

**To Reproduce**
It happens randomly

**Expected behavior**
This error shouldn't happen

**Environment**
OS and device (ie. Raspbian on RaspberryPI): OctoPi 0.17.0 on raspberry pi 4
Java version (check with java -version): 
java version "1.8.0_212"
Java(TM) SE Runtime Environment (build 1.8.0_212-b10)
Java HotSpot(TM) Client VM (build 25.212-b10, mixed mode)

**Additional information**
Ruuvi-collector is running in screen. InfluxDB and Grafana are hosted on my linode server and not locally on rpi.
RPI4 is connected to the internet through wifi. It is also running octoprint for my 3d printer, that's why octopi distro. It is based on raspbian

**Comment by DG12** [comment] 2020-07-26 01:16
This looks like an (intermittent ?) problem with resolving darkball.net (nothing to do with ruuvicollector).
How often does this occur.
Are you seeing other network related errors in other logs? Like wifi dropouts? DNS lookup failures?

Does ruuviCollector restart successfully?
What is in  /lib/systemd/system/ruuvicollector.service ?

Does it include:
Restart=always
I have included a delay with:
RestartSec=300

Does ExecStart specify a script ? what is in it?  
Can you add a ping darkball.net to the end (to be executed after ruuvicollector aborts) .
better yet something like 
`curl --get 'http://darkbell.net:8086/query?' --data-urlencode "db=ruuvi" --data-urlencode "q=SELECT last(temperature) FROM ruuvi_measurements "`

**Comment by ikoutone** [comment] 2020-07-26 05:50
No other network related errors from what I can see. It's random, happened twice during 3 days. 
I haven't put it as a service, so I closed it with ctrl+c in screen and then restarted with "java -jar ruuvi-collector-*.jar" command. 

Would changing the domain to IP of my server help? That way there wouldn't be a need for dns lookup.

**Comment by Scrin** [comment] 2020-07-26 10:40
The error is indeed caused by a failure in resolving the domain, it could be a (temporary, short) hiccup in your network/internet, it could be whatever dns server your rapsberry is configured to use, usually the one provided by your ISP if you haven't changed it.
If the issue is with your dns server and you can't fix that, you can use the direct IP instead to overcome the issue, or at least rule out any dns related issues if this happens to be a case of multiple issues with similar symptoms.

**Comment by DG12** [comment] 2020-07-26 12:35
Setting it up as a service would at least have it restart without your intervention and using a script would allow execution of additional diagnostic actions.

What is in /etc/resolv.conf (that the DNS server to be used) I would expect it to be your router like 192.168.1.1.

I would think the most fragile section of your network is the wifi portion. Can you ethernet wire the pi to the router?

**Comment by ikoutone** [comment] 2020-07-30 03:15
I looked at the logs of my modem and saw that it was optimizing wireless at the time disconnection happened.

> 30.07.20` 04:21:37 Wireless auto channel: Current detection of the wireless LAN environment (5 GHz) in progress, in order to optimize the wireless channels in use; some wireless devices may be re-registered.
30.07.20 04:21:43 Wireless device was deregistered (5 GHz), octopi
30.07.20 04:21:49 Wireless device registered (5 GHz), 150 Mbit/s, octopi

Ruuvitag message around the same time.
> Jul 30, 2020 4:21:55 AM org.influxdb.impl.BatchProcessor write
SEVERE: Batch could not be sent. Data will be lost
org.influxdb.InfluxDBIOException: java.net.SocketTimeoutException: timeout

So most likely this dns lookup error happened while it was doing optimization. 

As to resolv.conf, it is set to 192.168.0.1. I could wire the pi, but I'd rather not have ethernet cable laying around for that.

**Comment by Scrin** [comment] 2020-07-30 08:01
So the issue indeed is that your modem disconnects your Pi briefly for "optimization", you could probably either turn off this "optimization" or just ignore the error. You will of course lose the datapoint(s) during this disconnect, but since the disconnect seems to be rather short I don't think its a big issue. 

This particular error is just a temporary error, the collector will automatically resume normal operation when the connectivity is restored. If it does not and just keeps repeating the same error over and over again, then it's something else

**Closed by Scrin** 2020-07-30 08:01 UTC
Labels: bug, unconfirmed

**Comment by DG12** [comment] 2020-07-30 12:06
@ikoutone thanks for reporting what you found.
